### PR TITLE
README edits

### PR DESCRIPTION
**Pull request by divya-mohan0209**
Edits made to the Readme to convey
- What is Kubeslice
- How is it different/Why is it needed
- How can users get onboarded
- How can they provide feedback & join the community

### CODE REVIEW

**Review by eric978 — APPROVED** [review]
LGTM!

**Comment by eric978** [comment]
@divya-mohan0209 Hi Divya.   Just noticed these changes hadn't merged yet?    I approved them a while back.    Were you going to merge them in?   (I think they're good to go.)

**Comment by divya-mohan0209** [comment]
Hey @eric978 , I am actually awaiting the Slack channel creation + a bunch of other things. Once those are done, I will merge it in!

**Comment by divya-mohan0209** [comment]
Hey @eric978, @pnavali, @veenamj-avesha - whenever y'all are in please could you check and merge this? I don't have access to merge the PR since I don't have write access to the repo.

**Comment by eric978** [comment]
Merged

**Pull request merged**
